apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: lustre-client
spec: 
  metadata:
    namespace: lustre-client
  environment:
  - key: "key_id"
    value: "AWS_ACCESS_KEY_ID"
  - key: "access_key"
    value: "AWS_SECRET_ACCESS_KEY"
  driverContainer:
    source:
      git:
        ref: "master"
        uri: "https://github.com/dagrayvid/driver-containers.git"
    buildArgs:
    - name: "KVER"
      value: "{{.KernelVersion}}"

  dependsOn: 
  - name: "driver-container-base"
    imageReference: "true"
